<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>GanttCreator.Raster</RootNamespace>
    <AssemblyName>GanttCreator.Raster</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ExcelDna.Interop" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GanttCreator.Core\GanttCreator.Core.csproj" />
  </ItemGroup>
</Project>
