#requires -Version 7
<#
.SYNOPSIS
    Regenerate the .cline/skills/ tree from the canonical docs/ mirror.

.DESCRIPTION
    The kit has two views of the same content:

      docs/0N-*.md           canonical in-repo source of truth
      .cline/skills/0N-*/    on-demand skills (loaded when a Cline
                             session decides the description matches)

    Always-on rules live in AGENTS.md at the repository root and are
    hand-maintained; they are not regenerated by this script. The
    skills use progressive loading: Cline sees the ~100-token YAML
    front-matter at startup and loads the full SKILL.md body only
    when the conversation matches the description. When the summary
    is not enough, the skill's own "Where to read more" footer points
    directly at the canonical docs/0N-*.md file.

    This script regenerates ONLY .cline/skills/0N-*/SKILL.md from the
    canonical docs. It does not generate a references.md duplicate —
    a full-body copy of docs/0N-*.md under .cline/skills/ was removed
    (2026-09) because it cost real repo bytes and its own drift-gate
    machinery for zero information the canonical source didn't already
    provide at the same token cost. Loading docs/0N-*.md directly IS
    the "full reference" now.

    SKILL.md's summary is extracted from a hand-authored block in the
    canonical doc:

      <!-- SKILL-SUMMARY:START -->
      ... 5-15 lines: what this doc is for and what you must not get
      wrong ...
      <!-- SKILL-SUMMARY:END -->

    This replaces the previous "first N non-empty lines" truncation
    heuristic, which silently dropped load-bearing content whenever a
    doc edit pushed it past line 80 (that failure mode is why
    check-skill-summary.ps1 existed). A hand-authored, co-located
    summary block cannot drift from its source the way a separate
    summary file could, and cannot be silently truncated by doc growth.

    Until every docs/0N-*.md has a SKILL-SUMMARY block, this script
    falls back to the old truncation heuristic for that file and
    prints a warning. The fallback is deliberately non-fatal so this
    script keeps working during the migration; treat the warning as a
    to-do, not as an error to suppress.

    This script is idempotent; running it twice in a row produces the
    same output. docs/clinerules/SYNC.md explains the discipline;
    verify-quick.ps1 and verify.ps1 run scripts/check-cline-skills.ps1
    as a drift gate.
#>

[CmdletBinding()]
param(
    [string]$DocsRoot     = 'docs',
    [string]$SkillsRoot   = '.cline/skills',
    [int]   $SummaryLines = 80
)

$ErrorActionPreference = 'Stop'

# Source-of-truth file to skill-name + description map. A new
# docs/0N-*.md requires an explicit entry here.
$map = @{
    '01-ENVIRONMENT.md'        = @{ Name = '01-environment';  Description = 'Dev-machine baseline (.NET / Office / Visual Studio / Excel-DNA / VS Code versions), first-run installation checklist, common Office-host failures, and the offline acceptance check. Trigger on environment, setup, install, or version questions.' }
    '02-ARCHITECTURE.md'       = @{ Name = '02-architecture'; Description = 'Product boundary; one-visible-sheet + _GanttCreatorConfig contracts; scene-first rendering and renderer equivalence; COM ownership; binding C# and architecture conventions (nullable/analyzers, immutability, DateOnly, geometry rounding, DI boundaries, save/restore, XML doc). Trigger on architecture, worksheet-schema, COM, or C#-convention questions.' }
    '03-ROADMAP.md'            = @{ Name = '03-roadmap';      Description = 'Work-item list R0.x-R10.8 with per-item automated and Office gates, the cross-phase compatibility matrix, and the scope-change protocol. Trigger on which-work-item, which-phase, which-gate, or next-safe-action questions.' }
    '04-TEST-STRATEGY.md'      = @{ Name = '04-test-strategy';Description = 'Test layers, per-project coverage thresholds, the Core/raster/Office test catalogues, golden-image process, Office integration harness, fault injection, flaky-test policy, and PR test evidence. Trigger on writing or running tests, coverage, or golden-image questions.' }
    '05-GIT-QUALITY.md'        = @{ Name = '05-git-quality';  Description = 'Branch/review policy, commit design and Conventional Commit format, local gates (verify-quick.ps1 / verify.ps1), CI parity, PR template, review checklist, comment and dependency policy, and the release gate. Trigger on commit, PR, dependency, or release questions.' }
    '06-LLM-PROTOCOL.md'       = @{ Name = '06-llm-protocol'; Description = 'Required session opening, evidence ledger, anti-drift and anti-hallucination controls, the two-attempt no-loop protocol, context discipline, coding behaviour, prompt pattern, and the agent handoff format; plus the full-repo code-review methodology. Trigger on protocol, evidence, retry, or handoff-format questions.' }
    '07-GANTT-ENTITY-GUIDE.md' = @{ Name = '07-entity-guide'; Description = 'Entity geometry, style tokens, label positions, z-order, the minimum visual reference fixture, and the entity-to-renderer equivalence table. Largest skill; load docs/07-GANTT-ENTITY-GUIDE.md directly when the summary is not enough. Trigger on any visual, layout, style, or export question.' }
}

$summaryStartMarker = '<!-- SKILL-SUMMARY:START -->'
$summaryEndMarker   = '<!-- SKILL-SUMMARY:END -->'
$fallbackUsed       = @()

foreach ($root in @($DocsRoot, $SkillsRoot)) {
    if (-not (Test-Path -LiteralPath $root)) { New-Item -ItemType Directory -Path $root -Force | Out-Null }
}

# Validate that every mapped canonical source exists.
foreach ($file in $map.Keys) {
    $full = Join-Path $DocsRoot $file
    if (-not (Test-Path -LiteralPath $full)) { throw "Canonical source missing: $full" }
}

# Regenerate each skill.
foreach ($file in $map.Keys) {
    $src      = Join-Path $DocsRoot $file
    $entry    = $map[$file]
    $skillDir = Join-Path $SkillsRoot $entry.Name
    $skillMd  = Join-Path $skillDir 'SKILL.md'
    $body     = Get-Content -LiteralPath $src -Raw

    if (-not (Test-Path -LiteralPath $skillDir)) { New-Item -ItemType Directory -Path $skillDir -Force | Out-Null }

    # SKILL.md summary: hand-authored SKILL-SUMMARY block when present,
    # otherwise fall back to the first N non-empty lines (with a warning).
    $startIdx = $body.IndexOf($summaryStartMarker)
    $endIdx   = $body.IndexOf($summaryEndMarker)
    if ($startIdx -ge 0 -and $endIdx -gt $startIdx) {
        $summaryStart = $startIdx + $summaryStartMarker.Length
        $summary = $body.Substring($summaryStart, $endIdx - $summaryStart).Trim()
    }
    else {
        $fallbackUsed += $file
        Write-Warning "sync-cline-skills: $file has no SKILL-SUMMARY block; falling back to the first $SummaryLines non-empty lines. Add a <!-- SKILL-SUMMARY:START --> / <!-- SKILL-SUMMARY:END --> block to $file to fix this permanently."
        $nonEmpty = $body -split "`r?`n" | Where-Object { $_.Trim() -ne '' }
        $summary  = ($nonEmpty | Select-Object -First $SummaryLines) -join "`n"
    }

    $fmName        = $file.Replace('.md', '')
    $fmDescription = $entry.Description
    $skillLines = @(
        '---'
        "name: $fmName"
        "description: $fmDescription"
        '---'
        ''
        $summary
        ''
        '---'
        ''
        '## Where to read more'
        ''
        "- Full reference: ``docs/$file`` (this is the canonical source; there is no separate copy under .cline/skills/)"
        ''
    )
    Set-Content -LiteralPath $skillMd -Value ($skillLines -join "`n") -NoNewline -Encoding utf8
}

# Sanity check.
Get-ChildItem -Path $SkillsRoot -Directory | ForEach-Object {
    $p = Join-Path $_.FullName 'SKILL.md'
    if (-not (Test-Path -LiteralPath $p)) { throw "Missing $p" }
}

$count = (Get-ChildItem -Path $SkillsRoot -Directory).Count
Write-Host "sync-cline-skills: regenerated $count skills under $SkillsRoot"
if ($fallbackUsed.Count -gt 0) {
    Write-Host "sync-cline-skills: $($fallbackUsed.Count) skill(s) still using the line-truncation fallback: $($fallbackUsed -join ', ')"
}
exit 0
