#requires -Version 7
<#
.SYNOPSIS
    Regenerate the .cline/skills/ tree from the canonical docs/ mirror.

.DESCRIPTION
    The kit has two views of the same content:

      docs/0N-*.md           canonical in-repo source of truth
      .cline/skills/0N-*/    on-demand skills (loaded when a Cline
                             session decides the description matches)

    Always-on rules live in AGENTS.md at the repository root and are
    hand-maintained; they are not regenerated by this script. The
    skills use progressive loading: Cline sees the ~100-token YAML
    front-matter at startup and loads the full SKILL.md body only
    when the conversation matches the description. When the summary
    is not enough, the skill's own "Where to read more" footer points
    directly at the canonical docs/0N-*.md file.

    This script regenerates ONLY .cline/skills/0N-*/SKILL.md from the
    canonical docs. It does not generate a references.md duplicate —
    a full-body copy of docs/0N-*.md under .cline/skills/ was removed
    (2026-09) because it cost real repo bytes and its own drift-gate
    machinery for zero information the canonical source didn't already
    provide at the same token cost. Loading docs/0N-*.md directly IS
    the "full reference" now.

    SKILL.md's summary is extracted from a hand-authored block in the
    canonical doc:

      <!-- SKILL-SUMMARY:START -->
      ... 5-15 lines: what this doc is for and what you must not get
      wrong ...
      <!-- SKILL-SUMMARY:END -->

    This replaces the previous "first N non-empty lines" truncation
    heuristic, which silently dropped load-bearing content whenever a
    doc edit pushed it past line 80 (that failure mode is why
    check-skill-summary.ps1 existed). A hand-authored, co-located
    summary block cannot drift from its source the way a separate
    summary file could, and cannot be silently truncated by doc growth.

    The migration to hand-authored SKILL-SUMMARY blocks is complete: every
    docs/0N-*.md in the $map carries one. A canonical doc that is missing
    the block is therefore an ERROR, not a fallback: this script fails with
    a non-zero exit so a summary can never again be silently truncated or
    degraded by a heuristic. Add the block to the doc and re-run.

    Each canonical doc also carries a hand-authored tools block:

      <!-- SKILL-TOOLS:START -->
      ... MCP tools most relevant to this skill, one per line ...
      <!-- SKILL-TOOLS:END -->

    This block is the bridge from the skill's knowledge to the MCP tools
    that execute it. Without it, a skill tells the agent what to know but
    never which tool to reach for. A canonical doc missing this block is
    an ERROR: this script fails with a non-zero exit.

    This script is idempotent; running it twice in a row produces the
    same output. docs/clinerules/SYNC.md explains the discipline;
    verify-quick.ps1 and verify.ps1 run scripts/check-cline-skills.ps1
    as a drift gate.
#>

[CmdletBinding()]
param(
    [string]$DocsRoot     = 'docs',
    [string]$SkillsRoot   = '.cline/skills'
)

$ErrorActionPreference = 'Stop'

# Source-of-truth file to skill-name + description map. A new
# docs/0N-*.md requires an explicit entry here.
$map = @{
    '01-ENVIRONMENT.md'        = @{ Name = '01-environment';  Description = 'Dev-machine baseline (.NET / Office / Visual Studio / Excel-DNA / VS Code versions), first-run installation checklist, common Office-host failures, and the offline acceptance check. Trigger on environment, setup, install, or version questions.' }
    '02-ARCHITECTURE.md'       = @{ Name = '02-architecture'; Description = 'Product boundary; one-visible-sheet + _GanttCreatorConfig contracts; scene-first rendering and renderer equivalence; COM ownership; binding C# and architecture conventions (nullable/analyzers, immutability, DateOnly, geometry rounding, DI boundaries, save/restore, XML doc). Trigger on architecture, worksheet-schema, COM, or C#-convention questions.' }
    '03-ROADMAP.md'            = @{ Name = '03-roadmap';      Description = 'Work-item list R0.x-R10.8 with per-item automated and Office gates, the cross-phase compatibility matrix, and the scope-change protocol. Trigger on which-work-item, which-phase, which-gate, or next-safe-action questions.' }
    '04-TEST-STRATEGY.md'      = @{ Name = '04-test-strategy';Description = 'Test layers, per-project coverage thresholds, the Core/raster/Office test catalogues, golden-image process, Office integration harness, fault injection, flaky-test policy, and PR test evidence. Trigger on writing or running tests, coverage, or golden-image questions.' }
    '05-GIT-QUALITY.md'        = @{ Name = '05-git-quality';  Description = 'Branch/review policy, commit design and Conventional Commit format, local gates (verify-quick.ps1 / verify.ps1), CI parity, PR template, review checklist, comment and dependency policy, and the release gate. Trigger on commit, PR, dependency, or release questions.' }
    '06-LLM-PROTOCOL.md'       = @{ Name = '06-llm-protocol'; Description = 'Required session opening, evidence ledger, anti-drift and anti-hallucination controls, the two-attempt no-loop protocol, context discipline, coding behaviour, prompt pattern, and the agent handoff format; plus the full-repo code-review methodology. Trigger on protocol, evidence, retry, or handoff-format questions.' }
    '07-GANTT-ENTITY-GUIDE.md' = @{ Name = '07-entity-guide'; Description = 'Entity geometry, style tokens, label positions, z-order, the minimum visual reference fixture, and the entity-to-renderer equivalence table. Largest skill; load docs/07-GANTT-ENTITY-GUIDE.md directly when the summary is not enough. Trigger on any visual, layout, style, or export question.' }
}

$summaryStartMarker = '<!-- SKILL-SUMMARY:START -->'
$summaryEndMarker   = '<!-- SKILL-SUMMARY:END -->'
$toolsStartMarker   = '<!-- SKILL-TOOLS:START -->'
$toolsEndMarker     = '<!-- SKILL-TOOLS:END -->'

# Only create the generated-output root. The docs/ root is the canonical
# source of truth; if it is missing, let the per-file validation below report
# "Canonical source missing" rather than silently masking the absence.
if (-not (Test-Path -LiteralPath $SkillsRoot)) { New-Item -ItemType Directory -Path $SkillsRoot -Force | Out-Null }

# Validate that every mapped canonical source exists.
foreach ($file in $map.Keys) {
    $full = Join-Path $DocsRoot $file
    if (-not (Test-Path -LiteralPath $full)) { throw "Canonical source missing: $full" }
}

# Validate that every canonical doc matching the docs/0N-*.md pattern has a
# $map entry. A doc without one is invisible to the sync script and the drift
# gate will not catch it; fail-fast so the gap is visible rather than silent.
$discoveredDocs = Get-ChildItem -LiteralPath $DocsRoot -File -Filter '0N-*.md' |
    Select-Object -ExpandProperty Name
foreach ($doc in $discoveredDocs) {
    if (-not $map.ContainsKey($doc)) {
        Write-Error ("sync-cline-skills: {0} matches the canonical docs/0N-*.md pattern but has no " +
                     "$map entry. Add an entry to $map in scripts/sync-cline-skills.ps1 and re-run." -f $doc)
        exit 1
    }
}

# Delete obsolete generated files and directories in the skills root that are
# not present in the current $map, including removed references.md entries.
# This ensures the skills root does not accumulate stale files when docs are
# removed from the map or when the generation format changes (e.g. the
# references.md files that were removed in 2026-09).
if (Test-Path -LiteralPath $SkillsRoot) {
    $managedNames = $map.Values.Name
    Get-ChildItem -LiteralPath $SkillsRoot -Directory | ForEach-Object {
        $dirName = $_.Name
        if ($dirName -notin $managedNames) {
            Write-Host "sync-cline-skills: removing obsolete skill directory '$dirName'"
            Remove-Item -LiteralPath $_.FullName -Recurse -Force -ErrorAction SilentlyContinue
        }
        else {
            # For managed skill directories, remove obsolete files (e.g.
            # references.md) that are no longer generated.
            Get-ChildItem -LiteralPath $_.FullName -File | Where-Object { $_.Name -ne 'SKILL.md' } |
                ForEach-Object {
                    Write-Host "sync-cline-skills: removing obsolete file '$($_.FullName)'"
                    Remove-Item -LiteralPath $_.FullName -Force -ErrorAction SilentlyContinue
                }
        }
    }
}

# Regenerate each skill.
foreach ($file in $map.Keys) {
    $src      = Join-Path $DocsRoot $file
    $entry    = $map[$file]
    $skillDir = Join-Path $SkillsRoot $entry.Name
    $skillMd  = Join-Path $skillDir 'SKILL.md'
    $body     = Get-Content -LiteralPath $src -Raw

    if (-not (Test-Path -LiteralPath $skillDir)) { New-Item -ItemType Directory -Path $skillDir -Force | Out-Null }

    # SKILL.md summary: the hand-authored SKILL-SUMMARY block is required.
    # A doc without one fails the sync (the old truncation fallback is gone
    # now that every mapped doc carries a block) so a summary can never be
    # silently truncated by doc growth again.
    $startIdx = $body.IndexOf($summaryStartMarker)
    $endIdx   = $body.IndexOf($summaryEndMarker)
    if ($startIdx -ge 0 -and $endIdx -gt $startIdx) {
        $summaryStart = $startIdx + $summaryStartMarker.Length
        $summary = $body.Substring($summaryStart, $endIdx - $summaryStart).Trim()
        if ([string]::IsNullOrWhiteSpace($summary)) {
            Write-Error ("sync-cline-skills: {0} has an empty SKILL-SUMMARY block. Every canonical doc must carry a " +
                         "non-empty <!-- SKILL-SUMMARY:START --> / <!-- SKILL-SUMMARY:END --> block; add content to {0} and re-run." -f $file)
            exit 1
        }
    }
    else {
        Write-Error ("sync-cline-skills: {0} has no SKILL-SUMMARY block. Every canonical doc must carry a " +
                     "<!-- SKILL-SUMMARY:START --> / <!-- SKILL-SUMMARY:END --> block; add one to {0} and re-run." -f $file)
        exit 1
    }

    # SKILL.md tools: the hand-authored SKILL-TOOLS block is required.
    # It lists the MCP tools most relevant to this skill and when to
    # reach for them. A doc without one fails the sync so a skill can
    # never again ship without a tool bridge.
    $toolsStartIdx = $body.IndexOf($toolsStartMarker)
    $toolsEndIdx   = $body.IndexOf($toolsEndMarker)
    if ($toolsStartIdx -ge 0 -and $toolsEndIdx -gt $toolsStartIdx) {
        $toolsStart = $toolsStartIdx + $toolsStartMarker.Length
        $tools = $body.Substring($toolsStart, $toolsEndIdx - $toolsStart).Trim()
        if ([string]::IsNullOrWhiteSpace($tools)) {
            Write-Error ("sync-cline-skills: {0} has an empty SKILL-TOOLS block. Every canonical doc must carry a " +
                         "non-empty <!-- SKILL-TOOLS:START --> / <!-- SKILL-TOOLS:END --> block; add content to {0} and re-run." -f $file)
            exit 1
        }
    }
    else {
        Write-Error ("sync-cline-skills: {0} has no SKILL-TOOLS block. Every canonical doc must carry a " +
                     "<!-- SKILL-TOOLS:START --> / <!-- SKILL-TOOLS:END --> block; add one to {0} and re-run." -f $file)
        exit 1
    }

    $fmName        = $file.Replace('.md', '')
    $fmDescription = $entry.Description
    $skillLines = @(
        '---'
        "name: $fmName"
        "description: $fmDescription"
        '---'
        ''
        $summary
        ''
        '---'
        ''
        '## Tools'
        ''
        $tools
        ''
        '---'
        ''
        '## Where to read more'
        ''
        "- Full reference: ``docs/$file`` (this is the canonical source; there is no separate copy under .cline/skills/)"
        ''
    )
    Set-Content -LiteralPath $skillMd -Value ($skillLines -join "`n") -NoNewline -Encoding utf8
}

# Sanity check.
Get-ChildItem -Path $SkillsRoot -Directory | ForEach-Object {
    $p = Join-Path $_.FullName 'SKILL.md'
    if (-not (Test-Path -LiteralPath $p)) { throw "Missing $p" }
}

$count = (Get-ChildItem -Path $SkillsRoot -Directory).Count
Write-Host "sync-cline-skills: regenerated $count skills under $SkillsRoot"
exit 0
