// <auto-generated>
//   Advance widths for the Aptos and Aptos Narrow families, read from the real
//   font binaries. DO NOT EDIT BY HAND -- regenerate with
//   scripts/gen-font-advances.py, which is committed for exactly that reason.
// </auto-generated>
#nullable enable

namespace GanttCreator.Core.Scene;

/// <summary>
/// Glyph advance widths, in font design units, for the families the label
/// typography tokens use.
/// </summary>
/// <remarks>
/// <para>
/// These are the fonts' own <c>hmtx</c> advances, not an approximation. The
/// previous table was a flat 4pt per character, which is wrong in BOTH
/// directions: measured against a live Excel textbox at 8pt, 40 characters of
/// <c>W</c> is 287.03pt where the flat table said 160pt (44 percent too small),
/// and 40 characters of <c>i</c> is 78.03pt where it said 160pt (105 percent
/// too large). The small end is what clips a label: the scene sized the box from
/// the underestimate and the host has no auto-size to recover the difference.
/// </para>
/// <para>
/// Regular and Bold of both families are carried, which covers the typography
/// tokens at 8pt regular, 8pt bold, 9pt bold and 11pt bold.
/// </para>
/// </remarks>
internal static class FontAdvanceTable
{
    /// <summary>The shared design-unit denominator.</summary>
    internal const int UnitsPerEm = 2048;

    /// <summary>The first code point in the ASCII run, U+0020.</summary>
    internal const int AsciiFirst = 0x20;

    /// <summary>One past the last code point in the ASCII run, U+007E.</summary>
    internal const int AsciiLast = 0x7E;

    internal static readonly ushort[] AptosRegularAscii =
    [
        416, 600, 757, 1100, 1094, 1692, 1317, 431, 600, 600, 936, 1094,
        585, 697, 585, 695, 1094, 1094, 1094, 1094, 1094, 1094, 1094, 1094,
        1094, 1094, 585, 585, 1094, 1094, 1094, 1027, 1832, 1207, 1237, 1418,
        1405, 1139, 1074, 1451, 1448, 533, 678, 1164, 1023, 1618, 1446, 1500,
        1182, 1500, 1241, 1159, 980, 1395, 1199, 1827, 1132, 1105, 1056, 603,
        695, 603, 1094, 942, 1130, 1088, 1149, 1075, 1148, 1079, 617, 992,
        1129, 489, 489, 997, 533, 1747, 1129, 1130, 1149, 1148, 685, 995,
        662, 1144, 926, 1476, 906, 926, 897, 603, 553, 603, 1094,
    ];
    internal static readonly ushort[] AptosBoldAscii =
    [
        416, 600, 860, 1100, 1094, 1723, 1386, 475, 600, 600, 936, 1094,
        614, 697, 614, 792, 1094, 1094, 1094, 1094, 1094, 1094, 1094, 1094,
        1094, 1094, 614, 614, 1094, 1094, 1094, 1060, 1843, 1270, 1268, 1447,
        1448, 1174, 1099, 1470, 1493, 602, 751, 1276, 1048, 1681, 1480, 1510,
        1240, 1510, 1298, 1225, 1035, 1426, 1263, 1926, 1227, 1200, 1121, 690,
        792, 690, 1094, 942, 1130, 1130, 1201, 1124, 1200, 1139, 686, 1047,
        1186, 549, 549, 1094, 606, 1821, 1186, 1174, 1201, 1200, 756, 1056,
        728, 1191, 1011, 1559, 1014, 1011, 954, 690, 553, 690, 1094,
    ];
    internal static readonly ushort[] AptosNarrowRegularAscii =
    [
        383, 667, 695, 1020, 1038, 1558, 1204, 394, 623, 623, 1020, 1038,
        533, 627, 533, 641, 1038, 1038, 1038, 1038, 1038, 1038, 1038, 1038,
        1038, 1038, 533, 533, 1038, 1038, 1038, 932, 1651, 1094, 1132, 1296,
        1284, 1043, 983, 1323, 1323, 498, 625, 1069, 935, 1479, 1320, 1367,
        1083, 1367, 1137, 1063, 893, 1271, 1087, 1665, 1035, 1009, 963, 554,
        641, 554, 1038, 852, 1022, 998, 1053, 982, 1053, 994, 570, 921,
        1038, 459, 459, 917, 497, 1606, 1038, 1034, 1053, 1053, 633, 907,
        607, 1045, 848, 1344, 831, 848, 818, 554, 946, 554, 1038,
    ];
    internal static readonly ushort[] AptosNarrowBoldAscii =
    [
        370, 667, 773, 1020, 1038, 1541, 1249, 424, 628, 628, 1020, 1038,
        546, 627, 546, 724, 1038, 1038, 1038, 1038, 1038, 1038, 1038, 1038,
        1038, 1038, 546, 546, 1038, 1038, 1038, 941, 1568, 1132, 1143, 1298,
        1296, 1054, 985, 1313, 1337, 557, 682, 1151, 941, 1504, 1323, 1347,
        1115, 1347, 1166, 1102, 922, 1265, 1125, 1720, 1099, 1078, 1002, 622,
        724, 622, 1038, 829, 994, 1022, 1085, 1016, 1085, 1036, 622, 944,
        1076, 515, 516, 988, 556, 1650, 1076, 1059, 1085, 1086, 688, 941,
        654, 1075, 912, 1386, 910, 912, 855, 622, 955, 622, 1038,
    ];

    /// <summary>
    /// Code points carried outside ASCII, in the order the <c>*Extra</c> arrays
    /// use: no-break space, en dash, em dash, left and right single quote, left
    /// and right double quote, ellipsis, multiplication sign, bullet.
    /// </summary>
    /// <remarks>A zero means the font has no glyph, which is a real answer.</remarks>
    internal static readonly int[] ExtraCodePoints =
    [        0x00A0, 0x2013, 0x2014, 0x2018, 0x2019, 0x201C,        0x201D, 0x2026, 0x00D7, 0x2022,    ];
    internal static readonly ushort[] AptosRegularExtra =
    [
        416, 942, 1884, 553, 553, 926, 927, 1675, 1094, 962,
    ];
    internal static readonly ushort[] AptosBoldExtra =
    [
        416, 942, 1884, 610, 610, 1063, 1065, 1741, 1094, 999,
    ];
    internal static readonly ushort[] AptosNarrowRegularExtra =
    [
        383, 852, 1704, 506, 506, 876, 876, 1621, 1038, 875,
    ];
    internal static readonly ushort[] AptosNarrowBoldExtra =
    [
        370, 829, 1657, 546, 546, 992, 993, 1669, 1038, 885,
    ];

    /// <summary>
    /// The advance for one code point, or 0 when the font carries no glyph.
    /// </summary>
    /// <param name="codePoint">The Unicode code point.</param>
    /// <param name="bold">Whether to read the bold face.</param>
    /// <param name="narrow">Whether to read the Narrow family.</param>
    /// <returns>The advance in design units, or 0 when the glyph is absent.</returns>
    internal static int AdvanceFor(int codePoint, bool bold, bool narrow)
    {
        ushort[] ascii = (narrow, bold) switch
        {
            (false, false) => AptosRegularAscii,
            (false, true) => AptosBoldAscii,
            (true, false) => AptosNarrowRegularAscii,
            (true, true) => AptosNarrowBoldAscii,
        };

        if (codePoint >= AsciiFirst && codePoint <= AsciiLast)
        {
            return ascii[codePoint - AsciiFirst];
        }

        ushort[] extra = (narrow, bold) switch
        {
            (false, false) => AptosRegularExtra,
            (false, true) => AptosBoldExtra,
            (true, false) => AptosNarrowRegularExtra,
            (true, true) => AptosNarrowBoldExtra,
        };

        for (int index = 0; index < ExtraCodePoints.Length; index++)
        {
            if (ExtraCodePoints[index] == codePoint)
            {
                return extra[index];
            }
        }

        return 0;
    }
}
